### ISSUE TITLE
MODELO DE NEGOCIOS

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-ggar#1]
[MODELO_DE_NEGOCIOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-ggar/files/9648752/MODELO_DE_NEGOCIOS.pdf)

**Comment by mel-16** [comment]
19% bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
